%% ============== 0. 环境 ==============
clear; clc; close all;
set(0,'defaultfigurecolor','w');
set(0,'defaultAxesFontName','Times New Roman', ...
      'defaultAxesFontSize',16);

%% ============== 1. 载入数据 ==============
f_ind  = '../../Data/Simu/Revision/SE_Independent_OMP_LoS_Low_N_10000_Antenna_1_new.mat';
f_nind = '../../Data/Simu/Revision/SE_NotIndependent_OMP_LoS_Low_N_10000_Antenna_1.mat';

S_ind  = load(f_ind);
S_nind = load(f_nind);

% → 取第 2 条链路 (10000 × 12)
SEup_ind  = squeeze(S_ind.SE_up(:,2,:));   % Independent,   upstream
SEdn_ind  = squeeze(S_ind.SE_dn(:,2,:));   % Independent,   downstream
SEup_nind = squeeze(S_nind.SE_up(:,2,:));  % Not-Independent, upstream
SEdn_nind = squeeze(S_nind.SE_dn(:,2,:));  % Not-Independent, downstream

% ── 对 10000 维度做均值 ──
SEup_ind  = mean(SEup_ind, 1);   % 对 10000 维度做均值
SEdn_ind  = mean(SEdn_ind, 1);   % 对 10000 维度做均值
SEup_nind = mean(SEup_nind, 1);  % 对 10000 维度做均值
SEdn_nind = mean(SEdn_nind, 1);  % 对 10000 维度做均值

% ── 元数据（列标签） ──
P_all    = S_ind.P_C_all(:).';      % 1×12
N_all    = S_ind.N_all(:).';        % 1×12
HPBW_all = S_ind.HPBW_all(:).';     % 1×12  (45…65…)

%% ============== 2. 已知列分组索引 ==============
idx_45_11 = 1:4;      % HPBW=45°, Np=11
idx_65_11 = 5:8;      % HPBW=65°, Np=11
idx_65_9  = 9:12;     % HPBW=65°, Np=9
P_set     = [27 29 31 33];   % 横轴

%% ============== 3. 公共绘图样式 ==============
clr_ind   = [0 0.447 0.741];   % 蓝：Independent
clr_nind  = [0.850 0.325 0.098]; % 红：Not-Independent
ls_up = '-';      % 实线：SE_up
ls_dn = '--';     % 虚线：SE_dn
mksize = 12;

% 图 1 & 图 2 : 各 8 条曲线、8 个独特 marker
markers_fig1 = {'o','s','^','v','d','p','h','*'};
markers_fig2 = {'x','+','>','<','pentagram','hexagram','square','diamond'};

%% ============== 4-1. 图 1 — HPBW=45°, Np=11 与 HPBW=65°, Np=11 ==========
figure; hold on; box on; grid on;
mk = markers_fig1; k = 1;

% --- 45°, Np=11 ---
plot(P_set, SEup_ind(1,idx_45_11), ...
     'Color',clr_ind,'LineStyle',ls_up,'LineWidth',2, ...
     'Marker',mk{k},'MarkerSize',mksize, 'MarkerFaceColor','none', ...
     'DisplayName','Indep SE_{up}, HPBW=45°, N_p=11'); k=k+1;
plot(P_set, SEdn_ind(1,idx_45_11), ...
     'Color',clr_ind,'LineStyle',ls_dn,'LineWidth',2, ...
     'Marker',mk{k},'MarkerSize',mksize, 'MarkerFaceColor','none', ...
     'DisplayName','Indep SE_{dn}, HPBW=45°, N_p=11'); k=k+1;
plot(P_set, SEup_nind(1,idx_45_11), ...
     'Color',clr_nind,'LineStyle',ls_up,'LineWidth',2, ...
     'Marker',mk{k},'MarkerSize',mksize, 'MarkerFaceColor','none', ...
     'DisplayName','NotInd SE_{up}, HPBW=45°, N_p=11'); k=k+1;
plot(P_set, SEdn_nind(1,idx_45_11), ...
     'Color',clr_nind,'LineStyle',ls_dn,'LineWidth',2, ...
     'Marker',mk{k},'MarkerSize',mksize, 'MarkerFaceColor','none', ...
     'DisplayName','NotInd SE_{dn}, HPBW=45°, N_p=11'); k=k+1;

% --- 65°, Np=11 ---
plot(P_set, SEup_ind(1,idx_65_11), ...
     'Color',clr_ind,'LineStyle',ls_up,'LineWidth',2, ...
     'Marker',mk{k},'MarkerSize',mksize, 'MarkerFaceColor','none', ...
     'DisplayName','Indep SE_{up}, HPBW=65°, N_p=11'); k=k+1;
plot(P_set, SEdn_ind(1,idx_65_11), ...
     'Color',clr_ind,'LineStyle',ls_dn,'LineWidth',2, ...
     'Marker',mk{k},'MarkerSize',mksize, 'MarkerFaceColor','none', ...
     'DisplayName','Indep SE_{dn}, HPBW=65°, N_p=11'); k=k+1;
plot(P_set, SEup_nind(1,idx_65_11), ...
     'Color',clr_nind,'LineStyle',ls_up,'LineWidth',2, ...
     'Marker',mk{k},'MarkerSize',mksize, 'MarkerFaceColor','none', ...
     'DisplayName','NotInd SE_{up}, HPBW=65°, N_p=11'); k=k+1;
plot(P_set, SEdn_nind(1,idx_65_11), ...
     'Color',clr_nind,'LineStyle',ls_dn,'LineWidth',2, ...
     'Marker',mk{k},'MarkerSize',mksize, 'MarkerFaceColor','none', ...
     'DisplayName','NotInd SE_{dn}, HPBW=65°, N_p=11');

xlabel('Transmit Power P_C (dBm)');
ylabel('SE [bit/s/Hz]');
title('Figure 1:  HPBW = 45° & 65°  (N_p = 11)');
legend('Location','northwest');

%% ============== 4-2. 图 2 — HPBW=65°, Np=11 与 HPBW=65°, Np=9 ==========

figure; hold on; box on; grid on;
mk = markers_fig2; k = 1;

% --- 65°, Np=11 ---
plot(P_set, SEup_ind(1,idx_65_11), ...
     'Color',clr_ind,'LineStyle',ls_up,'LineWidth',2, ...
     'Marker',mk{k},'MarkerSize',mksize, 'MarkerFaceColor','none', ...
     'DisplayName','Indep SE_{up}, HPBW=65°, N_p=11'); k=k+1;
plot(P_set, SEdn_ind(1,idx_65_11), ...
     'Color',clr_ind,'LineStyle',ls_dn,'LineWidth',2, ...
     'Marker',mk{k},'MarkerSize',mksize, 'MarkerFaceColor','none', ...
     'DisplayName','Indep SE_{dn}, HPBW=65°, N_p=11'); k=k+1;
plot(P_set, SEup_nind(1,idx_65_11), ...
     'Color',clr_nind,'LineStyle',ls_up,'LineWidth',2, ...
     'Marker',mk{k},'MarkerSize',mksize, 'MarkerFaceColor','none', ...
     'DisplayName','NotInd SE_{up}, HPBW=65°, N_p=11'); k=k+1;
plot(P_set, SEdn_nind(1,idx_65_11), ...
     'Color',clr_nind,'LineStyle',ls_dn,'LineWidth',2, ...
     'Marker',mk{k},'MarkerSize',mksize, 'MarkerFaceColor','none', ...
     'DisplayName','NotInd SE_{dn}, HPBW=65°, N_p=11'); k=k+1;

% --- 65°, Np=9 ---
plot(P_set, SEup_ind(1,idx_65_9), ...
     'Color',clr_ind,'LineStyle',ls_up,'LineWidth',2, ...
     'Marker',mk{k},'MarkerSize',mksize, 'MarkerFaceColor','none', ...
     'DisplayName','Indep SE_{up}, HPBW=65°, N_p=9'); k=k+1;
plot(P_set, SEdn_ind(1,idx_65_9), ...
     'Color',clr_ind,'LineStyle',ls_dn,'LineWidth',2, ...
     'Marker',mk{k},'MarkerSize',mksize, 'MarkerFaceColor','none', ...
     'DisplayName','Indep SE_{dn}, HPBW=65°, N_p=9'); k=k+1;
plot(P_set, SEup_nind(1,idx_65_9), ...
     'Color',clr_nind,'LineStyle',ls_up,'LineWidth',2, ...
     'Marker',mk{k},'MarkerSize',mksize, 'MarkerFaceColor','none', ...
     'DisplayName','NotInd SE_{up}, HPBW=65°, N_p=9'); k=k+1;
plot(P_set, SEdn_nind(1,idx_65_9), ...
     'Color',clr_nind,'LineStyle',ls_dn,'LineWidth',2, ...
     'Marker',mk{k},'MarkerSize',mksize, 'MarkerFaceColor','none', ...
     'DisplayName','NotInd SE_{dn}, HPBW=65°, N_p=9');

xlabel('Transmit Power P_C (dBm)');
ylabel('SE [bit/s/Hz]');
title('Figure 2:  HPBW = 65°  (N_p = 11 & 9)');
legend('Location','northwest');
