%% ========== 环境 ==========
clear; clc; close all;
set(0,'defaultfigurecolor','w');
set(0,'defaultAxesFontName','Times New Roman','defaultAxesFontSize',16);

%% ========== 加载数据 ==========
N_it  = 10000;
N_ant = 4;

A_OMP_Org = load(sprintf('../Data/Simu/OMP_LoS_Original_N_%d_Antenna_%d.mat',N_it,N_ant)).Angle_Error;
A_OMP_Low = load(sprintf('../Data/Simu/OMP_LoS_Low_N_%d_Antenna_%d.mat'     ,N_it,N_ant)).Angle_Error;
A_MUS_Org = load(sprintf('../Data/Simu/MUSIC_LoS_Original_N_%d_Antenna_%d.mat',N_it,N_ant)).Angle_Error;

%% ========== 样式定义 ==========
styles = { ...
  struct('Color',[0.85 0.33 0.10],'LineStyle','-','Marker','o'), ...  % 1
  struct('Color',[0.00 0.45 0.74],'LineStyle','--','Marker','s'), ... % 2
  struct('Color',[0.47 0.67 0.19],'LineStyle',':','Marker','^'), ...  % 3
  struct('Color',[0.00 0.00 0.00],'LineStyle','-.','Marker','d'), ... % 4
  struct('Color',[0.75 0.00 0.75],'LineStyle','-','Marker','v'), ...  % 5
  struct('Color',[0.93 0.69 0.12],'LineStyle','--','Marker','x') ...  % 6
};

%% ========== 1. Jammer – 不同天线数 ==========
titles = { ...
  'N_p = 7, OMP', ...
  'N_p = 9, OMP', ...
  'N_p = 11, OMP', ...
  'N_p = 11, MUSIC', ...
  'N_p = 11, OMP, Low' };
data   = { ...
  A_OMP_Org(:,1,1), ...
  A_OMP_Org(:,1,2), ...
  A_OMP_Org(:,1,3), ...
  A_MUS_Org(:,1,3), ...
  A_OMP_Low(:,1,3) ...
};

figure; hold on; box on; grid on;
hs = gobjects(1,numel(data));
for i = 1:numel(data)
    hgrp = cdfplot(abs(data{i}));
    h   = findobj(hgrp,'Type','Line');
    st  = styles{i};
    x   = get(h,'XData');
    mi  = round(linspace(1,numel(x),20));
    set(h, 'Color',st.Color, ...
           'LineStyle',st.LineStyle, ...
           'LineWidth',1.8, ...
           'Marker',st.Marker, ...
           'MarkerSize',8, ...
           'MarkerIndices',mi);
    set(hgrp,'HandleVisibility','off');
    hs(i)=h;
end
xlabel('\xi_J [deg]');
ylabel('CDF');
title('Different Number of Antennas – Jammer');
legend(hs, titles, 'Location','southeast','Box','off');

%% ========== 2. Jammer – 不同 HPBW ==========
% 假设 OMP_Org 的 3rd dim: 3→HPBW=65, 4→45, 5→25, 6→15
idx = [6,5,4,3];  % 15,25,45,65 顺序
titles = { ...
  'HPBW = 15° OMP', ...
  'HPBW = 25° OMP', ...
  'HPBW = 45° OMP', ...
  'HPBW = 65° OMP', ...
  'HPBW = 65° MUSIC', ...
  'HPBW = 65° OMP, Low' };
data   = [ arrayfun(@(k) A_OMP_Org(:,1,k), idx,'uni',0), ...
           { A_MUS_Org(:,1,3), A_OMP_Low(:,1,3) } ];

figure; hold on; box on; grid on;
hs = gobjects(1,numel(data));
for i = 1:numel(data)
    hgrp = cdfplot(abs(data{i}));
    h   = findobj(hgrp,'Type','Line');
    st  = styles{i};
    x   = get(h,'XData');
    mi  = round(linspace(1,numel(x),20));
    set(h, 'Color',st.Color, ...
           'LineStyle',st.LineStyle, ...
           'LineWidth',1.8, ...
           'Marker',st.Marker, ...
           'MarkerSize',8, ...
           'MarkerIndices',mi);
    set(hgrp,'HandleVisibility','off');
    hs(i)=h;
end
xlabel('\xi_J [deg]');
ylabel('CDF');
title('Different HPBW – Jammer');
legend(hs, titles, 'Location','southeast','Box','off');

%% ========== 3. Jammer – 不同功率 ==========
% 假设 dims: index 3→27 dBm, 7→29, 8→31, 9→33
idx = [3,7,8,9];
titles = { ...
  'P_C = 27 dBm OMP', ...
  'P_C = 29 dBm OMP', ...
  'P_C = 31 dBm OMP', ...
  'P_C = 33 dBm OMP', ...
  'P_C = 27 dBm MUSIC', ...
  'P_C = 27 dBm OMP, Low' };
data   = [ arrayfun(@(k) A_OMP_Org(:,1,k), idx,'uni',0), ...
           { A_MUS_Org(:,1,1), A_OMP_Low(:,1,1) } ];

figure; hold on; box on; grid on;
hs = gobjects(1,numel(data));
for i = 1:numel(data)
    hgrp = cdfplot(abs(data{i}));
    h   = findobj(hgrp,'Type','Line');
    st  = styles{i};
    x   = get(h,'XData');
    mi  = round(linspace(1,numel(x),20));
    set(h, 'Color',st.Color, ...
           'LineStyle',st.LineStyle, ...
           'LineWidth',1.8, ...
           'Marker',st.Marker, ...
           'MarkerSize',8, ...
           'MarkerIndices',mi);
    set(hgrp,'HandleVisibility','off');
    hs(i)=h;
end
xlabel('\xi_J [deg]');
ylabel('CDF');
title('Different Transmit Power – Jammer');
legend(hs, titles, 'Location','southeast','Box','off');

%% ========== 4. Controller – 不同天线数 ==========
titles = { ...
  'N_p = 7, OMP', ...
  'N_p = 9, OMP', ...
  'N_p = 11, OMP', ...
  'N_p = 11, MUSIC', ...
  'N_p = 11, OMP, Low' };
data   = { ...
  A_OMP_Org(:,2,1), ...
  A_OMP_Org(:,2,2), ...
  A_OMP_Org(:,2,3), ...
  A_MUS_Org(:,2,3),   ...
  A_OMP_Low(:,2,3)    ...
};

figure; hold on; box on; grid on;
hs = gobjects(1,numel(data));
for i = 1:numel(data)
    hgrp = cdfplot(abs(data{i}));
    h   = findobj(hgrp,'Type','Line');
    st  = styles{i};
    x   = get(h,'XData');
    mi  = round(linspace(1,numel(x),20));
    set(h, 'Color',st.Color, ...
           'LineStyle',st.LineStyle, ...
           'LineWidth',1.8, ...
           'Marker',st.Marker, ...
           'MarkerSize',8, ...
           'MarkerIndices',mi);
    set(hgrp,'HandleVisibility','off');
    hs(i)=h;
end
xlabel('\xi_C [deg]');
ylabel('CDF');
title('Different Number of Antennas – Controller');
legend(hs, titles, 'Location','southeast','Box','off');

%% ========== 5. Controller – 不同 HPBW ==========
idx = [6,5,4,3]; % 15,25,45,65 顺序
titles = { ...
  'HPBW = 15° OMP', ...
  'HPBW = 25° OMP', ...
  'HPBW = 45° OMP', ...
  'HPBW = 65° OMP', ...
  'HPBW = 65° MUSIC', ...
  'HPBW = 65° OMP, Low' };
data   = [ arrayfun(@(k) A_OMP_Org(:,2,k), idx,'uni',0), ...
           { A_MUS_Org(:,2,3), A_OMP_Low(:,2,3) } ];

figure; hold on; box on; grid on;
hs = gobjects(1,numel(data));
for i = 1:numel(data)
    hgrp = cdfplot(abs(data{i}));
    h   = findobj(hgrp,'Type','Line');
    st  = styles{i};
    x   = get(h,'XData');
    mi  = round(linspace(1,numel(x),20));
    set(h, 'Color',st.Color, ...
           'LineStyle',st.LineStyle, ...
           'LineWidth',1.8, ...
           'Marker',st.Marker, ...
           'MarkerSize',8, ...
           'MarkerIndices',mi);
    set(hgrp,'HandleVisibility','off');
    hs(i)=h;
end
xlabel('\xi_C [deg]');
ylabel('CDF');
title('Different HPBW – Controller');
legend(hs, titles, 'Location','southeast','Box','off');

%% ========== 6. Controller – 不同功率 ==========
idx = [3,7,8,9];
titles = { ...
  'P_C = 27 dBm OMP', ...
  'P_C = 29 dBm OMP', ...
  'P_C = 31 dBm OMP', ...
  'P_C = 33 dBm OMP', ...
  'P_C = 27 dBm MUSIC', ...
  'P_C = 27 dBm OMP, Low' };
data   = [ arrayfun(@(k) A_OMP_Org(:,2,k), idx,'uni',0), ...
           { A_MUS_Org(:,2,1), A_OMP_Low(:,2,1) } ];

figure; hold on; box on; grid on;
hs = gobjects(1,numel(data));
for i = 1:numel(data)
    hgrp = cdfplot(abs(data{i}));
    h   = findobj(hgrp,'Type','Line');
    st  = styles{i};
    x   = get(h,'XData');
    mi  = round(linspace(1,numel(x),20));
    set(h, 'Color',st.Color, ...
           'LineStyle',st.LineStyle, ...
           'LineWidth',1.8, ...
           'Marker',st.Marker, ...
           'MarkerSize',8, ...
           'MarkerIndices',mi);
    set(hgrp,'HandleVisibility','off');
    hs(i)=h;
end
xlabel('\xi_C [deg]');
ylabel('CDF');
title('Different Transmit Power – Controller');
legend(hs, titles, 'Location','southeast','Box','off');
